etcd:
  image: flynn/etcd
  net: host

apiserver:  
  image: nebelpfade/hyperkube 
  net: host
  command: ["/hyperkube", "apiserver", "--service-cluster-ip-range=172.17.17.1/24", "--insecure-bind-address=127.0.0.1", "--etcd_servers=http://localhost:4001", "--cluster_name=kubernetes", "--v=2"]

controller:  
  image: nebelpfade/hyperkube
  net: host
  command: ["/hyperkube", "controller-manager", "--master=127.0.0.1:8080", "--v=2"]

scheduler:  
  image: nebelpfade/hyperkube 
  net: host
  command: ["/hyperkube", "scheduler", "--master=127.0.0.1:8080", "--v=2"]

kubelet:  
  image: nebelpfade/hyperkube 
  net: host
  command: ['/hyperkube', 'kubelet', '--api_servers=http://127.0.0.1:8080', '--v=2', '--address=0.0.0.0', '--enable_server']
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock