kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2017-01-17T19:14:38Z
  name: filebeat-config
  namespace: default
data:
  simple-config.yml: |-
    filebeat:
      prospectors:
        -
          input_type: stdin
        -
          input_type: log
          paths:
            - "/tmp/*.log"
            #- c:\programdata\elasticsearch\logs\*
          document_type: app-hello
          tail_files: true
    output:
      console:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - name: hello
        image: silentred/hello:v3
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /tmp
          name: log-vol
        # env:
        #   - name: CONFIG_FOO
        #     valueFrom:
        #       configMapKeyRef:
        #         name: my-config
        #         key: example.foo
      - name: filebeat
        image: silentred/filebeat
        args:
          - '-c=/etc/filebeat/simple-config.yml'
        volumeMounts:
        - name: fb-config-vol
          mountPath: /etc/filebeat
        - mountPath: /tmp
          name: log-vol

      volumes:
      - name: fb-config-vol
        configMap:
          name: filebeat-config
      - name: log-vol
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: hello
  name: hello
spec:
  type: NodePort
  ports:
  - port: 9090
  selector:
    run: hello